name: Build

on:
  push:
    branches:
      - main
      - cli_setup
  pull_request:
    branches: [ main ]
  workflow_dispatch:

  release:
    types: 
      - published
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Restore dependencies
        run: dotnet restore Aper_bot
        
      - name: Build
        run: dotnet build Aper_bot --no-restore
        
      - name: Test
        run: dotnet test Aper_bot.Test --no-build --verbosity normal
  
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    needs: test

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Lovercase name
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: preparereg_Names
        id: package_names
        run: |
          DOCKER_IMAGE=ghcr.io/${{ steps.string.outputs.lowercase }}
          VERSION=edge
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          elif [ "${{ github.event_name }}" = "release" ]; then
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          echo ::set-output name=tags::${TAGS}

      - name: Echo Info
        run: |
          echo $GITHUB_ENV
          echo $IMAGE_REPOSITORY
          echo ${{ github.repository }}
          echo ${{ steps.string.outputs.lowercase }}

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.package_names.outputs.tags }}
